---
- name: Install Docker Dependencies
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common 
  tags: docker

- name: Get Docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: Ddd Docker packages to Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
  tags: docker

- name: Install Docker-CE
  apt: name="docker-ce" state=latest update_cache=yes
  tags: docker
